-- MySQL Script generated by MySQL Workbench
-- Mon Jun 16 16:04:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel` ;

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guest` ;

CREATE TABLE IF NOT EXISTS `guest` (
  `idguest` INT NOT NULL,
  `guest_floor` INT NULL,
  `guest_number` INT NULL,
  `guest_category` VARCHAR(200) NULL,
  `guest_name` VARCHAR(100) NULL,
  `guest_in` DATE NULL,
  `guest_out` DATE NULL,
  `room_idroom` INT NOT NULL,
  PRIMARY KEY (`idguest`, `room_idroom`),
  INDEX `fk_guest_room1_idx` (`room_idroom` ASC) VISIBLE,
  CONSTRAINT `fk_guest_room1`
    FOREIGN KEY (`room_idroom`)
    REFERENCES `room` (`idroom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `report` ;

CREATE TABLE IF NOT EXISTS `report` (
  `idreport` INT NOT NULL,
  `report_category` VARCHAR(200) NULL,
  `report_status` VARCHAR(50) NULL,
  `report_date` DATE NULL,
  `room_idroom` INT NOT NULL,
  PRIMARY KEY (`idreport`, `room_idroom`),
  INDEX `fk_report_room_idx` (`room_idroom` ASC) VISIBLE,
  CONSTRAINT `fk_report_room`
    FOREIGN KEY (`room_idroom`)
    REFERENCES `room` (`idroom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `room` ;

CREATE TABLE IF NOT EXISTS `room` (
  `idroom` INT NOT NULL,
  `room_floor` INT NULL,
  `room_number` INT NULL,
  `room_category` VARCHAR(200) NULL,
  PRIMARY KEY (`idroom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `idusers` INT NOT NULL,
  `user_role` VARCHAR(45) NULL,
  `user_login` VARCHAR(45) NULL,
  `user_password` VARCHAR(45) NULL,
  `is_blocked` TINYINT(1) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
